import { describe, expect, it } from "vitest";
import { deterministicItemId } from "./deterministicId";

describe("deterministicItemId", () => {
  // Fixtures generated by running the backend's OWN generateDeterministicId
  // (backend/src/shared/util/generateUuidFromCobissId.ts) under node on
  // 2026-09-20. If one of these ever fails, the backend changed its id
  // derivation and `resolveExistingRecord`'s fast path is stale — the
  // cobissId verification there means that degrades safely, but fix it.
  it.each([
    ["12345", "cbwkbr9guqs3w11xylpri1ylw"],
    ["1024", "c29acqe7cabtjuh28m580qhzg"],
    ["77", "c364tkc05vg2amt5266ezbs1z"],
  ])("matches the backend for %s", async (cobissId, expected) => {
    expect(await deterministicItemId(cobissId)).toBe(expected);
  });

  it("is always 25 characters and 'c'-prefixed", async () => {
    const id = await deterministicItemId("999999");
    expect(id).toHaveLength(25);
    expect(id.startsWith("c")).toBe(true);
  });
});
